---
title: "07_Davis_Shannon_2018"
author: "Shannon Davis"
date: "October 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(broom)
library(viridis)
library(profileModel)
library(bbmle)
```

##1. Grid Sampling! Based on Friday's lab, load up the pufferfish data and use grid sampling to find the MLE of the slope, intercept and residual SD of this model. Feel free to eyeball results from an lm() fit to get reasonable values. Try not to do this for a grid of more than ~100K points (more if you want!). It's ok to be coarse. Compare to lm.

```{R}
phish <- read_csv("../data/16q11PufferfishMimicry.csv")

head(phish)

#look at relationship (linear)

phish_lm <- lm(predators ~ resemblance, data = phish)
summary(phish_lm)

#plot data 
ggplot(data = phish,
       mapping = aes(x = resemblance, y = predators))+
  geom_point()

#1 write function

phish_like_fun <- function(slope, intercept, resid_sd){
  #data generation
  pred_hat <- intercept + slope + phish$resemblance
  
  #liklihood
  sum(dnorm(phish$predators, pred_hat, resid_sd, log=TRUE))
}

#where should we be sampling
summary(phish_lm)

#setup our grid 
phish_grid <- crossing(intercept = seq(0.5, 2.5, 0.1),
                          slope = seq(2, 5, 0.1),
                       resid_sd = seq(2.9, 3.1, 0.01))%>%
  rowwise()%>%
  mutate(phish_log_like = phish_like_fun(slope, intercept, resid_sd))%>%
  ungroup()

#look at ML

phish_grid %>% filter(phish_log_like==max(phish_log_like))

```
intercept from lm is 1.92 and slope is 2.99. I used this as a guidline for grid sampling. 

##2. Surfaces! Filter the dataset to the MLE of the SD. Plot the surface for the slope and intercept in whatever way you find most compelling. You might want to play around with zooming in to different regions, etc. Have fun!

```{R}
ggplot(phish_grid %>% filter(resid_sd == 2.9)
       %>%   filter(phish_log_like >  max(phish_log_like) - 4),
       aes(x = intercept, y = slope, fill = exp(phish_log_like))) +
  geom_raster()

```

##3. GLM! Now, compare those results to results from glm. Show the profiles and confidence intervals from glm() for the slope and intercept.

```{R}
phish_glm <- glm(predators ~ resemblance, data = phish,
                 family = gaussian(link = "identity"))
#gives slope and intercept
summary(phish_glm)


phish_glm_prof <- profileModel(phish_glm,
                               objective = "ordinaryDeviance",
                               quantile = qchisq(0.95,1))

plot(phish_glm_prof)


#confidence interval
confint(phish_glm)
```

##4. Get Outside of GLM! So, often, we have more complex models than the above. There are a variety of optimizers out there, and packages for accessing them. One of the best is bbmle by Ecologist Ben Bolker (whose dad is emeritus at UMB in computer science! Go visit him! He's fantastic!)


###Load up 'bbmle and try out mle2. It's a bit different, in that the first argument is a function that minimizes the log likelihood (not maximizes). The second argument is a list of start values - e.g.  list(slope = 2, intercept = 5, resid_sd = 2). Try and fit your model with mle2 using start values close to the actual estimates. Look at the summary and plot the profile. Note, you might get a lot of errors because it will try impossible values of your residual SD. Also, note thatyou'll have to rewrite your likelihood function to return the negative log likelihood (or write a wrapper that does so). A small thing

```{R}
phish_min_like <- function(slope, intercept, resid_sd){
  -phish_like_fun(slope, intercept, resid_sd)
}

#slope = ~2, intercept = ~1, resid_sd = ~ 3
phish_mle2 <- mle2(phish_min_like,
                   start = list(slope = 2, intercept =1, resid_sd = 3))

summary(phish_mle2)


```

##5. Start values! What happens if you start with start values very far away from the initial values. Failing here is fine. But what do you think is happening, and what does this say about the value of start values?

```{R}

#high values
phish_mle2_high <- mle2(phish_min_like,
                   start = list(slope = 1000, intercept =1000, resid_sd = 1000))

summary(phish_mle2_high)


#low values
phish_mle2_low <- mle2(phish_min_like,
                   start = list(slope = 0.01, intercept =0.01, resid_sd = 0.01))

summary(phish_mle2_low)

```
When the high values are put into the function a convergence error is stated. This doesn't happen with the low numbers (probably becasue they are not that differnet from the actual values). This just shows that the start value can drastically alter the outcome of the function and create a lot of problems if they are guessed wrong.

##6. Algorithms! By default, mle2 uses the Nelder-Mead algorithm via the optim function. What happens if you add an method argument to "SANN" or "L-BFGS-B" (and for the later, which is bounded sampling, give it a lower argument for your residual value, so it's always positive). See  ?optim for some more guidance. Do these both converge to the same value? Based on their profiles, do you trust them? (Note, Simulated annealing takes a looooong time. Go have a cuppa while the profile for that one runs).

```{R}
#sann
phish_sann <- mle2(phish_min_like,
                    start = list(slope = 1.9, intercept = 1, resid_sd = 3),
                    method = "SANN")

summary(phish_sann)

plot(profile(phish_sann))

#L-bfgs-B
phish_lbfgsb <- mle2(phish_min_like, 
                    start = list(slope = 1.9, intercept = 1, resid_sd = 3),
          method = "L-BFGS-B",
          lower=c(resid_sd = 1e-10))


plot(profile(phish_lbfgsb))
summary(phish_lbfgsb)

```

both have similar profiles, but very different results. 
