---
title: "Midterm_Davis_Shannon_2018"
author: "Shannon Davis"
date: "October 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(broom)
library(viridis)
library(profileModel)
library(bbmle)
library(brms)
library(bayesplot)
library(purrr)
```

#Midterm Exam
##Biol 607
##October 26, 2018
##Welcome to your mid-term! I hope you enjoy. Note, in all of the questions below, there are easy not so code intensive ways of doing it, and there are longer more involved, yet still workable ways to answer them. I would suggest that before you dive into analyses, you do the following. First, breathe. Second, think about the steps you need to execute to get answer the question. Write them down. Third, for those parts of problems that require code, put those steps, in sequence, in comments in your script file. Use those as signposts to step-by-step walk through the things you need to do. Fourth, go over these steps, and see if there are any that could be easily abstracted into functions, could be vectorized, or otherwise done so that you can expend the minimum amount of effort on the problem to get the correct answer.

###You will be graded on
###1. Correct answers
###2. Showing how you arrived at that answer
###3. Well formatted and documented code
###4. Thoughtful answers


###The exam will be due on Nov 9th, 5pm.

##1) Sampling your system (10 points)
###Each of you has a study system your work in and a question of interest. Give an example of one variable that you would sample in order to get a sense of its variation in nature. Describe, in detail, how you would sample for the population of that variable in order to understand its distribution. Questions to consider include, but are not limited to: Just what is your sample versus your population? What would your sampling design be? Why would you design it that particular way? What are potential confounding influences of both sampling technique and sample design that you need to be careful to avoid? What statistical distribution might the variable take, and why?

What would you sample to understand systems variation in nature? 
I study carbon fluxes during rain events in small, urban, terminal rivers. TO understand the variability of flow in a specific river, hourly flow rates could be used. 


How would you sample for the population of that variable to understand distibution?
Sampling one river hourly would represnet the varibility of the river flow. 

Sample vs population
In this case the sample are discreate samples every hour. The population is the flow of the river at any given time. The population is infinate/continous, while the sample is finite/discreate.

sampling design? why?
This hourly sampling design allows for a reasonable use of a sensor while still getting good coverage of the whole time series. If we sampled any more, the sensor battery woud not last long enough or hold enough data. If we sampled any less we would miss out on some extreemly high flow rates, because the highest of high flow rates normally only last for 15 minutes or so. An hour between sampels allows for good coverage while still staying within the use of the sensor. 

confounding influence of both sampling technique or design that need to be avoided.
When the river has a low flow it tends to stay low for a long time. When the river is high, it is much more flashy and only stays at the highest flow rate for 15 minutes. This means that we could be missing the highest flow rates. 

What statistical distribution might be the variable take?
This distribution should look like a normal distibution with a right skew (weighted to the low flow). 


##2) Let's get philosophical. (10 points)
###Are you a frequentist, likelihoodist, or Bayesian? Why? Include in your answer why you prefer the inferential tools (e.g. confidence intervals, test statistics, posterior probabilities, etc.) of your chosen worldview and why you do not like the ones of the other one. This includes defining just what those different tools mean! extra credit for citing and discussing outside sources - one point per source/point

To start out I am going to eliminate likelihoods from the possibilities. Likelihoodism does not do much to provide guidance for what you should believe about a system. The result of a likelihood analysis is not as useful as Bayes of frequentist for making decisions and that is why it is out of the competition for my preferred statistical method. 

So now we have Bayesian vs Frequentist. Both give guidance on what conclusions we can make. Bayes gives you the probability of your hypothesis given the data and frequency gives you the probability of your data given the hypothesis. The former is a more "English friendly" way of explaining statistics, but before I can make my decision, lets dig a little deeper. 

Bayesian use likelihood combined with prior knowledge to make a judgment on what the data is saying. Frequentist use likelihood to create a repeatable test to see what the probability of rejecting the null hypothesis is. The best way to explain this is the following joke. 

"A Bayesian is one who, vaguely expecting a horse, and catching a glimpse of a donkey, strongly believes he has seen a mule." (Bayesian Fun)

This is basically saying that your glimpse of a donkey completely changes the way you see the problem. If you were trying to determine the probability of seeing a horse, and you were a frequentist the fact you saw a donkey would not change your probability at all. 

At this point I am leaning toward frequentist, due to the fact that you do not need prior knowledge. The final point that pushes frequentist to the font is that confidence intervals, where you can say how confident you are that a range of values holds the true mean of the population. For me, this is a very useful tool, and pushes frequentist to victory! 


##3) Power (20 points)
###We have a lot of aspects of the sample of data that we collect which can alter the power of our linear regressions.

###Slope
###Intercept
###Residual variance
###Sample Size
###Range of X values
###Choose three of the above properties and demonstrate how they alter power of an F-test from a linear regression using at least three different alpha levels (more if you want!) As a baseline of the parameters, let's use the information from the seal data:

###slope = 0.00237, intercept=115.767, sigma = 5.6805, range of seal ages = 958 to 8353, or, if you prefer, seal ages ??? N(3730.246, 1293.485). Your call what distribution to use for seal age simulation.

```{R}
seals <- read_csv("../Data/17e8ShrinkingSeals Trites 1996.csv")
head(seals)
hist(seals$age.days)

p_from_f_test <- function(samp_size = 10, slope = 0.00237, intercept = 115.767, sigma = 5.6805, min = 958, max = 8353){
 
  # Generate Normal Distribution for Seal Age 
  age.days <- runif(samp_size, min, max)
  
  # Generate Data for Seal Age and Seal Length 
  seal_data <- data.frame(intercept = intercept, sigma = sigma, age.days = age.days, 
                        length.cm = rnorm(samp_size, intercept + slope * age.days, sigma)) 
  # Compute Linear Regression
  seal_mod <- lm(length.cm~age.days, seal_data)
  # ANOVA 
  seal_anova <- anova(seal_mod)
  
  # Extract F-Test P-Value
  seal_p <- seal_anova$`Pr(>F)`[1]
  
  return(seal_p)
}

seal_start <- p_from_f_test()

seal_start

pow_from_f_test <- function(nsims = 1000, alpha =0.05, samp_size = 10, slope = 0.00237, intercept = 115.767, sigma = 5.6805, min = 958, max = 8353){
  
  # Apply p nsims times
  p <- replicate(nsims, p_from_f_test(samp_size, slope, intercept, sigma, min, max))
  
  # Calculate the number of p values that are incorrect given that we should be rejecting the null
  num_wrong <- sum(p > alpha)
  
  # Return power
  power <- 1 - num_wrong/nsims
  
  return(power)
}

#slope
pow_data_slope <- crossing(alpha_diff = c(0.001, 0.01, 0.05, 0.1),
                   size_diff = nrow(seals),
                   slope_diff = seq (0.001 ,0.003, 0.0001), 
                  intercept_diff = 115.767,
                   sigma_diff = 5.6805) %>%
                  
  rowwise() %>%
  mutate(power = pow_from_f_test(alpha = alpha_diff, 
                           slope = slope_diff)) %>%
  ungroup()


pow_data_slope


###slope_plot
slope_plot <- ggplot(pow_data_slope, 
                     mapping = aes(x = slope_diff, y = power, color = factor(alpha_diff)))+
  geom_point()+
  geom_line()

slope_plot


###sigma

pow_data_sigma <- crossing(alpha_diff = c(0.001, 0.01, 0.05, 0.1),
                   sigma_diff = seq(3, 8, 1)) %>%
                  
  rowwise() %>%
  mutate(power = pow_from_f_test(alpha = alpha_diff, 
                           sigma = sigma_diff)) %>%
  ungroup()


pow_data_sigma


###plot
sigma_plot <- ggplot(pow_data_sigma, 
                     mapping = aes(x = sigma_diff, y = power, color = factor(alpha_diff)))+
  geom_point()+
  geom_line()

sigma_plot


###intercept

pow_data_int <- crossing(alpha_diff = c(0.001, 0.01, 0.05, 0.1),
                  intercept_diff = seq(110,120, 1)) %>%
                  
  rowwise() %>%
  mutate(power = pow_from_f_test(alpha = alpha_diff, 
                           intercept = intercept_diff)) %>%
  ungroup()


pow_data_int


###plot
int_plot <- ggplot(pow_data_int, 
                     mapping = aes(x = intercept_diff, y = power, color = factor(alpha_diff)))+
  geom_point()+
  geom_line()

int_plot

###sample size

pow_data_size <- crossing(alpha_diff = c(0.001, 0.01, 0.05, 0.1),
                  size_diff = seq(5,40, 5)) %>%
                  
  rowwise() %>%
  mutate(power = pow_from_f_test(alpha = alpha_diff, 
                           samp_size =  size_diff)) %>%
  ungroup()


pow_data_size


###plot
size_plot <- ggplot(pow_data_size, 
                     mapping = aes(x = size_diff, y = power, color = factor(alpha_diff)))+
  geom_point()+
  geom_line()

size_plot
```





Change in intercept did not have a significant effect on power, increasing residual variance had a negative effect on power and larger sample sizes increased power. 



###Extra credit 1 - test whether the distribution of ages alters power: 3 points

```{R}

```

###Extra Credit 2 Choose just one of the above elements to vary. Using likelihood to fit models, repeat your power analysis for a chi-square likelihood ratio test. You can use glm(), bbmle or some other means of fitting and obtaining a LRT at your discretion. 5 points.

```{R}

```

##4) Bayes Theorem
###I've referenced the following figure a few times. I'd like you to demonstrate your understanding of Bayes Theorem by hand showing what the probability of the sun exploding is given the data. Assume that your prior probability that the sun explodes is p(Sun Explodes) = 0.0001. The rest of the information 
```{R}

P_SE <- 35/36 #probability that the dice says the sun is exploding  given that it is exploding 
P_E <- 0.0001 #probability the sun explodes 

#P(S) = P(S/E)*P(E)+P(S/N)*P(N)

P_SN <- 1/36 #probability that the dice is saying the sun exploded but it did not
P_N <- 1-P_E  #probaility of the sun not exploding 

P_S <- P_SE*P_E+P_SN*P_N

P_S #marginal (probability the dice says the sun exploded, regardless on if it explodes or not)


P_ES <- (P_SE * P_E)/P_S

P_ES  #probability the sun explodes given the dice tells you it is exploding 

```

##5) Quailing at the Prospect of Linear Models
###I'd like us to walk through the three different 'engines' that we have learned about to fit linear models. To motivate this, we'll look at Burness et al.'s 2012 study "Post-hatch heat warms adult beaks: irreversible physiological plasticity in Japanese quail http://rspb.royalsocietypublishing.org/content/280/1767/20131436.short the data for which they have made available at Data Dryad at http://datadryad.org/resource/doi:10.5061/dryad.gs661. We'll be looking at the morphology data.

##5.1 Three fits (10 points)
###To begin with, I'd like you to fit the relationship that describes how Tarsus (leg) length predicts upper beak (Culmen) length. Fit this relationship using least squares, likelihood, and Bayesian techniques. For each fit, demonstrate that the necessary assumptions have been met. Note, functions used to fit with likelihood and Bayes may or may not behave well when fed NAs. So look out for those errors.


```{R}
#load data
morph <- read.csv("../Data/Morphology data.csv") 

#least squares
morph_lm_mod <- lm(morph$Culmen..mm.~ morph$Tarsus..mm.)
#check assumptions 
plot(morph_lm_mod, which=1)  #check 
plot(morph_lm_mod, which=2) #check

#T-test
anova(morph_lm_mod) 
#summary of model 
summary(morph_lm_mod) 

morph_lm_plot <- ggplot(data = morph,
       mapping = aes(x = Tarsus..mm., y = Culmen..mm.))+
  geom_point()+
  stat_smooth(method=lm)

morph_lm_plot

```
This is a high F value. The F value is the ratio of two mean square values. If the null hypothesis is true, it is expected that F is close to 1. A large F value (like we have) means that the variation among group means is more than you'd expect to see by chance. Therefore we can reject the null hypothesis that leg length doesn't predict beak length.
```{R}
#likelihood
morph_glm_mod <- glm(Culmen..mm.~Tarsus..mm., 
                 data=morph,
                 family= gaussian(link="identity"))

#check assumptions 

plot(morph_glm_mod, which=1) #check
plot(morph_glm_mod, which=2) #check

morph_glm_plot <- ggplot(data = morph,
                         mapping = aes(x = Tarsus..mm., y = Culmen..mm.))+
  geom_point()+
  stat_smooth(method = "glm", method.args = list(family = gaussian(link=("identity"))))

morph_glm_plot
  


```

```{R}
# Bayes Setup
options(mc.cores = parallel::detectCores())
set.seed(607)

# Bayes brm
morph_brm_mod<- brm(Culmen..mm.~Tarsus..mm., 
                 data=morph,
                 family= gaussian(link="identity"))

plot(morph_brm_mod, which=1) #check
plot(morph_brm_mod, which=2) #check
# Plot 
bayes_chain <- as.data.frame(morph_brm_mod)

morph_brm_plot <- ggplot(data = morph, 
                         mapping = aes (x = Tarsus..mm., y = Culmen..mm.)) +
  geom_abline(intercept=bayes_chain[,1], slope = bayes_chain[,2], alpha=0.5, color="green") +
  geom_abline(intercept=fixef(morph_brm_mod)[1], slope = fixef(morph_brm_mod)[2], color="red") +
  geom_point()

morph_brm_plot
```
##5.2 Three interpretations (10 points)
###OK, now that we have fits, take a look! Do the coefficients and their associated measures of error in their estimation match? How would we interpret the results from these different analyses differently? Or would we? Note, confint works on lm objects as well.

```{R}
#least square
summary(morph_lm_mod)

#likelihood
summary(morph_glm_mod)

#Bayes
summary(morph_brm_mod)

```



##5.3 Everyday I'm Profilin' (10 points)
###For your likelihood fit, are your profiles well behaved? For just the slope, use grid sampling to create a profile. You'll need to write functions for this, and use the results from your glm() fit to provide the reasonable bounds of what you should be profiling over (3SE should do). Is it well behaved? Plot the profile and give the 80% and 95% CI. Verify your results with profileModel.

```{R}
# grid sample  Function
morph_fix <- morph %>%
  na.omit()

head(morph_fix)

likeFun <- function(slope, intercept, resid_sd){
  fit <- intercept + slope * morph_fix$Tarsus..mm.
  
  #Likelihood
  sum(dnorm(morph_fix$Culmen..mm., fit, resid_sd, log=TRUE))
  
}

# Combinations 
grid_morph <- crossing(intercept = seq(-.75, 0.5, 0.5),
                      slope = seq(0, 0.5,.001),
                      resid_sd = seq(0.5, 1.5, 0.01)) %>%
  rowwise() %>%
  mutate(logLike = likeFun(slope, intercept, resid_sd)) %>%
  ungroup()

head(grid_morph)

#log max 
slope_prof <-grid_morph %>% 
  group_by(slope) %>%
 filter(logLike == max(logLike))

#plot
ggplot(data = slope_prof,
       mapping = aes(x = slope, y = logLike))+
  geom_line()


#95%
morph_95 <- grid_morph %>%
  filter(logLike > max(logLike)- (qchisq(0.95,1)/2)) %>%
  arrange(slope)%>%
  filter(row_number()==1|row_number()==n())%>%
  select(slope)%>%
  as.data.frame

morph_95

#80%

morph_80 <- grid_morph %>%
  filter(logLike > max(logLike)- (qchisq(0.80,1)/2)) %>%
  arrange(slope)%>%
  filter(row_number()==1|row_number()==n())%>%
  select(slope)%>%
  as.data.frame

morph_80

ggplot(data = slope_prof,
       mapping = aes(x = slope, y = logLike))+
  geom_line()+
  geom_vline(data = morph_80,
             mapping = aes(xintercept = slope, color = "orange"))+
  geom_vline(data = morph_95,
             mapping = aes(xintercept = slope, color = "blue"))
       
```



##5.4 The Power of the Prior (10 points)
###This data set is pretty big. After excluding NAs in the variables we're interested in, it's over 766 lines of data! Now, a lot of data can overhwelm a strong prior. But only to a point. Show first that there is enough data here that a prior for the slope with an estimate of 0.4 and a sd of 0.01 is overwhelmed by the data by demonstrating that it produces similar results to our already fit flat prior. Second, see if a very small sample size (n = 10) would at least include 0.4 in it's 95% Credible Interval. Last, demonstrate at what sample size that 95% CL first begins to include 0.4 when we have a strong prior. How much data do we really need to overcome our prior belief? Note, it takes a long time to fit these models, so, try a strategy of spacing out the 3-4 sample sizes, and then zoom in on an interesting region.

```{R}

```

##6. Extra Credit
###Make an election forecast as discussed at https://biol607.github.io/extra.html - but this isn't just a winner prediction. 1 point for the correct winner. 5 points for correctly predicting the popular vote and being within 10% (3% just for trying!). 5 points for predicting the electoral college and geting no more than 5 states wrong (3 points just for trying). 5 points for predicting the senate races getting no more than 5 states wrong (3 points just for trying). 1 extra point for each vote percentage within your 80% Confidence/Credible Interval. Ditto for the house races.

```{R}

```

###If you want to do something else crazy with the election data, contact me, and we'll discuss how many extra points it would be worth (typically 3-5).

###Theoretically, you could almost pass this exam just by good forecasts.